sensors:
  - far_clipping_plane_distance: 2.0
    filtered_cloud_topic: filtered_cloud
    image_topic: /camera/aligned_depth_to_color/image_raw
    max_update_rate: 5.0
    near_clipping_plane_distance: 0.3
    padding_offset: 0.03
    padding_scale: 4.0
    queue_size: 5
    sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    shadow_threshold: 0.2